#!/usr/bin/env bash
# This file is copied into the application package as the entry point.
function boot:basher(){
  local BASHER_PATH="${0%/*}/basher-framework"
  # shellcheck source="$BASHER_PATH/app.sh"
  source "$BASHER_PATH/app.sh"

  # Add Your Commands Here.
  os:speak "BasherApp Build Successful"
  os:notify "BasherApp" "Build Successful"
}
boot:basher