#!/usr/bin/env bash
# This file is copied into the application package as the entry point.
# Execute Command: /usr/bin/env bash ~/Desktop/Basher.app/Contents/MacOS/basher "os:speak "test""
# open ~/Desktop/Basher.app --args "os:speak "test""

BASHER_PATH="${0%/*}/basher-framework"
# shellcheck source="$BASHER_PATH/app.sh"
source "$BASHER_PATH/app.sh"

# Add Your Commands Here.
#os:speak "BasherApp Build Successful"
os:notify "BasherApp" "Build Successful"

function logger:save(){
  echo "$1" >> "${0%/*}/../../../basher.log"
}

if str:filled "$1" && ! str:matches:regex "$1" -.*; then
  logger:save "$(logger:info "Executing: $1")"
  eval "$1"
fi
